# Generated by Django 4.2.5 on 2024-03-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobapp_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_Post', models.CharField(max_length=1000)),
                ('job_Company', models.CharField(max_length=1000)),
                ('job_Loc', models.CharField(max_length=1000)),
                ('job_Shift', models.CharField(max_length=1000)),
                ('job_Salary', models.IntegerField()),
            ],
            options={
                'db_table': 'jobapp',
            },
        ),
    ]
